/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example;

public class Greetings {
  /**
   * @param name Name to say hello
   */
  public static void hello(String name) {
    GreetingsJNI.hello(name);
  }

}
